name: Send Notification Every 30 Minutes

on:
  schedule:
    - cron: "*/30 * * * *"  # Every 30 minutes

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Check Python version
        run: python --version

      - name: Verify installed dependencies
        run: pip show requests || echo "requests not installed"

      - name: Install dependencies
        run: pip install requests

      - name: List files in workspace
        run: ls -R

      - name: Run the script
        env:
          PUSHSAFER_ACCESS_KEY: ${{ secrets.PUSHSAFER_ACCESS_KEY }}
        run: python main.py
